#!/usr/bin/env node
// Canonical examples catalog — build & maintenance engine.
//
// Deterministic (no LLM). Verifies every catalog entry still points at a real,
// lintable exemplar and emits an agent-friendly catalog. This is the "examples
// loop": maintaining examples costs a file-existence + lint check, not a
// regeneration, and every other loop starts from a known-good shape.
//
// Usage:
//   node tools/examples-catalog/build.mjs           # verify + write the catalog
//   node tools/examples-catalog/build.mjs --check   # verify only; exit 1 on drift
//                                                    # (CI / the loop's exit gate)

import { existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { examples, categories, appRoot, outFile } from './config.mjs';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const GENERATED = '<!-- GENERATED by tools/examples-catalog/build.mjs — do not hand-edit. Run `bun run examples:catalog`. -->';
const check = process.argv.includes('--check');

const abs = (p) => join(repoRoot, appRoot, p);
const rel = (p) => `${appRoot}/${p}`;

// --- verify: every pointer resolves; collect drift ---
const drift = [];
for (const ex of examples) {
  if (!existsSync(abs(ex.file))) drift.push(`${ex.id}: missing exemplar ${rel(ex.file)}`);
  if (ex.subject && !existsSync(abs(ex.subject))) drift.push(`${ex.id}: missing paired file ${rel(ex.subject)}`);
}

// --- optional lint gate: exemplars must still pass eslint (fast, source only) ---
// Skipped automatically when eslint is not installed, so the tool degrades like
// the repo-map engine instead of failing on a bare checkout.
let lintNote = 'lint check skipped (oxlint not installed)';
// Invoke oxlint the way the repo's own lint script does (bun run --bun) — the
// npm .bin shim under plain node fails to resolve the platform binary on
// bun-installed layouts (e.g. macOS darwin-arm64).
const oxlintBin = join(repoRoot, 'node_modules', 'oxlint', 'bin', 'oxlint');
if (existsSync(oxlintBin)) {
  const files = [...new Set(examples.flatMap((e) => [e.file, e.subject].filter(Boolean)))]
    .filter((f) => /\.(ts|tsx|js|mjs)$/.test(f))
    .map((f) => rel(f));
  try {
    execFileSync('bun', ['run', '--bun', oxlintBin, '--deny-warnings', ...files], {
      cwd: repoRoot,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    lintNote = `all ${files.length} exemplar files pass oxlint`;
  } catch (err) {
    const out = (err.stdout || '').toString() + (err.stderr || '').toString();
    drift.push(`oxlint failed on exemplar files:\n${out.split('\n').slice(-12).join('\n')}`);
    lintNote = 'oxlint FAILED on exemplar files (see drift)';
  }
}

if (check) {
  if (drift.length) {
    console.log('Examples catalog is STALE:\n- ' + drift.join('\n- '));
    process.exit(1);
  }
  console.log('Examples catalog is up to date.');
  process.exit(0);
}

if (drift.length) {
  // In build mode, still write what we can but surface the drift loudly.
  console.warn('WARNING — catalog drift:\n- ' + drift.join('\n- '));
}

// --- emit the catalog ---
const byCat = Object.entries(categories).map(([key, label]) => ({
  key,
  label,
  items: examples.filter((e) => e.category === key),
}));

const lines = [
  '# Canonical examples catalog',
  '',
  GENERATED,
  '',
  `> Source of truth: \`tools/examples-catalog/config.mjs\`. Exemplar status: ${lintNote}.`,
  '',
  'The reference shape for each kind of unit in this repo. Copy the linked exemplar',
  "instead of inventing a shape. Every entry points at real, in-repo code that",
  'passes lint and (where paired) ships with its test — no throwaway samples.',
  '',
];

for (const cat of byCat) {
  if (!cat.items.length) continue;
  lines.push(`## ${cat.label}`, '');
  for (const ex of cat.items) {
    lines.push(`### ${ex.title}`, '');
    lines.push(`- **Exemplar:** \`${rel(ex.file)}\``);
    if (ex.subject) lines.push(`- **Paired with:** \`${rel(ex.subject)}\``);
    lines.push(`- **When to use:** ${ex.whenToUse}`);
    lines.push('- **Shape:**');
    for (const s of ex.shape || []) lines.push(`  - ${s}`);
    lines.push('');
  }
}

lines.push('---', '', '_Maintained by the examples loop. Refresh with `npm run examples:catalog`; CI gates with `npm run examples:catalog:check`._', '');

const target = join(repoRoot, outFile);
writeFileSync(target, lines.join('\n'));
console.log(`examples-catalog: ${examples.length} exemplars verified → ${outFile}`);
