#!/usr/bin/env node
// Repo-map wide-scan engine — deterministic layer of "Wide Scan -> Deep Focus".
//
// Runs cheap, repeatable CLI signals (git history + import graph) *outside* any
// model's context window and writes a small set of agent-friendly artifacts:
//
//   context/map/artifact-1-territory.md      where the work actually happens
//   context/map/artifact-2-structure.md      how modules import each other + cycles
//   context/map/artifact-3-contributors.md   who has context on which area
//   context/map/repo-map.md                  the synthesized, decision-oriented map
//   context/map/graph/*                       raw graph outputs (cycles, metrics)
//
// This produces the *base* map for free. An agent using the `repo-map` skill
// layers a tailored Deep Focus on top for a specific request — fewer tool calls,
// less time, because the expensive territory work is already done and committed.
//
// Usage:
//   node tools/repo-map/scan.mjs            # full scan + synthesis
//   node tools/repo-map/scan.mjs --check    # regenerate to a temp dir and diff
//                                           # (CI uses this to detect staleness)

import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import config from './config.mjs';
import {
  git,
  run,
  isNoise,
  toArea,
  commitsWithFiles,
  rank,
  mdTable,
  resolveBin,
  quarter,
  isBotAuthor,
} from './lib.mjs';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const outDir = join(repoRoot, config.outDir);
const graphDir = join(outDir, 'graph');
const GENERATED = '<!-- GENERATED by tools/repo-map/scan.mjs — do not hand-edit. Run `npm run repo-map`. -->';

// The scan is stamped with the repo HEAD it described, not wall-clock time, so
// the output is reproducible: same commit in => same map out.
const head = git(['rev-parse', '--short', 'HEAD']);
const headDate = git(['show', '-s', '--format=%cs', 'HEAD']);
const windowLabel = `last ${config.since.replace(/ ago$/, '')}`; // "last 12 months"
const stamp = `Scan of \`${head}\` (${headDate}) · window: ${windowLabel} · engine: tools/repo-map`;

// ---------------------------------------------------------------------------
// 1. Territory — where the project lives (git history)
// ---------------------------------------------------------------------------
function scanTerritory(commits) {
  const areaCounts = new Map();
  const fileCounts = new Map();
  const quarterAreas = new Map(); // quarter -> Map(area -> count)
  const coChange = new Map(); // "a  +  b" -> count

  for (const c of commits) {
    const areas = new Set();
    for (const f of c.files) {
      const area = toArea(f, config.areaDepth);
      areaCounts.set(area, (areaCounts.get(area) || 0) + 1);
      fileCounts.set(f, (fileCounts.get(f) || 0) + 1);
      areas.add(area);
    }
    const q = quarter(c.date);
    if (!quarterAreas.has(q)) quarterAreas.set(q, new Map());
    const qa = quarterAreas.get(q);
    for (const a of areas) qa.set(a, (qa.get(a) || 0) + 1);
    // co-change: unordered pairs of areas touched together
    const sorted = [...areas].sort();
    for (let i = 0; i < sorted.length; i++)
      for (let j = i + 1; j < sorted.length; j++)
        coChange.set(`${sorted[i]}  +  ${sorted[j]}`, (coChange.get(`${sorted[i]}  +  ${sorted[j]}`) || 0) + 1);
  }

  const topAreas = rank(areaCounts, config.topN);
  const topFiles = rank(fileCounts, config.topN);
  const topCo = rank(coChange, 12).filter(([, n]) => n > 1);

  // quarterly trend for the top 5 areas
  const trendAreas = topAreas.slice(0, 5).map(([a]) => a);
  const quarters = [...quarterAreas.keys()].sort();
  const trendRows = trendAreas.map((a) => [
    `\`${a}\``,
    ...quarters.map((q) => String(quarterAreas.get(q).get(a) || 0)),
  ]);

  const md = [
    `# Artifact 1 — Territory`,
    ``,
    GENERATED,
    ``,
    `> ${stamp}`,
    ``,
    `**Where the work actually happens.** Git-history activity over the ${windowLabel}, noise filtered (lockfiles, generated files, assets). Activity is a signal of *risk of accidental regression*, not of quality.`,
    ``,
    `## Most active areas (commits touching path, depth ${config.areaDepth})`,
    ``,
    mdTable(['Area', 'Commits'], topAreas.map(([a, n]) => [`\`${a}\``, n])),
    ``,
    `## Most churned files`,
    ``,
    mdTable(['File', 'Commits'], topFiles.map(([f, n]) => [`\`${f}\``, n])),
    ``,
    `## Activity trend by quarter (top 5 areas)`,
    ``,
    mdTable(['Area', ...quarters], trendRows),
    ``,
    `## Co-change — areas that move together in the same commit`,
    ``,
    `Hidden neighbourhoods: these change together even when the folder tree suggests they are unrelated. History only — a co-change means "changed together", not "must change together".`,
    ``,
    topCo.length
      ? mdTable(['Pair of areas', 'Commits together'], topCo.map(([p, n]) => [p.replace(/`/g, ''), n]))
      : '_No repeated cross-area co-changes in the window._',
    ``,
  ].join('\n');

  return { md, topAreas, topFiles, topCo, commitsCount: commits.length };
}

// ---------------------------------------------------------------------------
// 2. Structure — how it is built (import graph)
// ---------------------------------------------------------------------------
function scanStructure(gd) {
  const madge = resolveBin('madge', repoRoot);
  const depcruise = resolveBin('depcruise', repoRoot);
  const ext = config.sourceExt.join(',');
  const primary = config.primaryModule;
  const limitations = [];

  // file inventory per module (static, no toolchain needed)
  const inventory = config.modules.map((m) => {
    const files = run('git', ['ls-files', m.root], { soft: true, cwd: repoRoot })
      .split('\n')
      .filter((f) => config.sourceExt.some((e) => f.endsWith('.' + e)) && !isNoise(f, config));
    return { ...m, files: files.length };
  });

  // circular dependencies (madge) on the primary module
  let cycles = [];
  const cyclesRaw = run(
    madge,
    ['--extensions', ext, '--circular', '--json', primary],
    { soft: true, cwd: repoRoot }
  );
  if (cyclesRaw) {
    try {
      cycles = JSON.parse(cyclesRaw);
    } catch {
      limitations.push('madge produced non-JSON output; cycle detection may be incomplete.');
    }
    writeFileSync(join(gd, 'cycles.json'), cyclesRaw + '\n');
  } else {
    limitations.push('madge not runnable (missing node_modules?) — cycles not detected this run.');
  }

  // fan-out (efferent coupling Ce) per folder (dependency-cruiser)
  let fanout = [];
  const metricsRaw = run(
    depcruise,
    [primary, '--no-config', '--metrics', '--output-type', 'json', '--exclude', config.graphExclude],
    { soft: true, cwd: repoRoot }
  );
  if (metricsRaw) {
    try {
      const parsed = JSON.parse(metricsRaw);
      // Keep folders with real content; drop the strict ancestors of the primary
      // module (`apps`, `apps/edu-platform`) that only aggregate everything below.
      const folders = (parsed.folders || []).filter(
        (f) => f.moduleCount > 3 && !primary.startsWith(f.name + '/')
      );
      fanout = folders
        .map((f) => ({
          name: f.name,
          ce: f.efferentCouplings ?? 0,
          ca: f.afferentCouplings ?? 0,
          count: f.moduleCount,
          instability: f.instability,
        }))
        .sort((a, b) => b.ce - a.ce)
        .slice(0, 12);
      // Persist only the compact folder-level coupling summary — the full module
      // graph is ~600KB of churn-per-run noise nobody reviews in a PR.
      const folderSummary = folders
        .map((f) => ({
          name: f.name,
          ce: f.efferentCouplings ?? 0,
          ca: f.afferentCouplings ?? 0,
          modules: f.moduleCount,
          instability: f.instability,
        }))
        .sort((a, b) => b.ce - a.ce);
      writeFileSync(
        join(gd, 'coupling.json'),
        JSON.stringify({ generatedFor: head, root: primary, folders: folderSummary }, null, 2) + '\n'
      );
    } catch {
      limitations.push('dependency-cruiser metrics JSON could not be parsed.');
    }
    // dependency-cruiser afferent coupling (Ca) needs a fully installed toolchain
    // to resolve every import; without it Ca under-reports. State it, do not hide it.
    limitations.push(
      'Afferent coupling (Ca) from dependency-cruiser is unreliable without a fully installed toolchain (external/aliased imports go unresolved). Treat Ca as a lower bound.'
    );
  } else {
    limitations.push('dependency-cruiser not runnable — coupling metrics skipped this run.');
  }
  limitations.push(
    'Static import graph only. Runtime wiring (dynamic import, template refs, feature flags, codegen) is invisible here and is an `unknown`, not "no dependency".'
  );

  const md = [
    `# Artifact 2 — Structure`,
    ``,
    GENERATED,
    ``,
    `> ${stamp}`,
    ``,
    `**How it is built.** Static import graph of \`${primary}\` plus a file inventory of every module. Folders show where the code is; the graph shows what actually depends on what.`,
    ``,
    `## Module inventory (source files, git-tracked)`,
    ``,
    mdTable(['Module', 'Root', 'Source files'], inventory.map((m) => [m.label, `\`${m.root}\``, m.files])),
    ``,
    `## Circular dependencies in \`${primary}\``,
    ``,
    cycles.length
      ? `${cycles.length} import cycle(s) found. Cycles are a classic source of hard-to-predict blast radius and prime Deep Focus targets.\n\n` +
        cycles
          .slice(0, 12)
          .map((c, i) => `${i + 1}. \`${c.join(' → ')} → ${c[0]}\``)
          .join('\n')
      : '_None detected this run._',
    ``,
    `## Highest fan-out folders (efferent coupling Ce — depends on many)`,
    ``,
    fanout.length
      ? mdTable(
          ['Folder', 'Ce (out)', 'Ca (in, lower bound)', 'Modules'],
          fanout.map((f) => [`\`${f.name}\``, f.ce, f.ca, f.count])
        )
      : '_Metrics unavailable this run (see limitations)._',
    ``,
    `## Limitations`,
    ``,
    limitations.map((l) => `- ${l}`).join('\n'),
    ``,
  ].join('\n');

  return { md, inventory, cycles, fanout, limitations };
}

// ---------------------------------------------------------------------------
// 3. Contributors — who has context on which area
// ---------------------------------------------------------------------------
function scanContributors(commits, topAreas) {
  // overall human contributor ranking
  const authorCounts = new Map();
  for (const c of commits) {
    if (isBotAuthor(c.author)) continue;
    authorCounts.set(c.author, (authorCounts.get(c.author) || 0) + 1);
  }
  const topAuthors = rank(authorCounts, 10);

  // per top-area: which humans touched it most
  const focusAreas = topAreas.slice(0, 6).map(([a]) => a);
  const areaAuthor = new Map(); // area -> Map(author -> count)
  for (const c of commits) {
    if (isBotAuthor(c.author)) continue;
    const touched = new Set(c.files.map((f) => toArea(f, config.areaDepth)));
    for (const a of touched) {
      if (!focusAreas.includes(a)) continue;
      if (!areaAuthor.has(a)) areaAuthor.set(a, new Map());
      const m = areaAuthor.get(a);
      m.set(c.author, (m.get(c.author) || 0) + 1);
    }
  }
  const areaRows = focusAreas.map((a) => {
    const people = rank(areaAuthor.get(a) || new Map(), 2)
      .map(([who, n]) => `${who} (${n})`)
      .join(', ');
    return [`\`${a}\``, people || '—'];
  });

  const md = [
    `# Artifact 3 — Contributors`,
    ``,
    GENERATED,
    ``,
    `> ${stamp}`,
    ``,
    `**Who to ask before you change something.** Bots and AI agents (Claude, Codex, Copilot, dependabot…) are filtered out — this is about humans who hold undocumented context. Answers "who has context on this area", not "who changed this line" (that is \`git blame\`).`,
    ``,
    `## Human contributors in the window`,
    ``,
    mdTable(['Contributor', 'Commits'], topAuthors.map(([a, n]) => [a, n])),
    ``,
    `## Who to ask, per active area`,
    ``,
    mdTable(['Area', 'Ask (commits)'], areaRows),
    ``,
  ].join('\n');

  return { md, topAuthors, areaRows };
}

// ---------------------------------------------------------------------------
// 4. Synthesis — the decision-oriented map
// ---------------------------------------------------------------------------
function synthesize({ territory, structure, contributors }) {
  const topArea = territory.topAreas[0];
  const layerNodes = structure.inventory
    .map((m) => `  ${m.app.replace(/[^a-zA-Z0-9]/g, '_')}["${m.label}<br/>${m.files} files"]`)
    .join('\n');

  // risk zones: cycles + sensitive api surface + high fan-out, mapped to evidence
  const riskZones = [];
  if (structure.cycles.length) {
    const hot = structure.cycles[0];
    riskZones.push([
      `\`${config.primaryModule}\` — import cycles`,
      `${structure.cycles.length} cycle(s), e.g. ${hot.slice(0, 3).join(' → ')}…`,
      `A change can ripple in a loop; hard to test in isolation. (madge)`,
    ]);
  }
  // Real sub-areas only — skip the `apps` / `apps/edu-platform` nesting parents
  // that just aggregate everything below the primary module.
  const leafFanout = structure.fanout.filter(
    (f) => f.name.startsWith(config.primaryModule + '/') && f.name.split('/').length <= config.primaryModule.split('/').length + 2
  );
  for (const f of leafFanout.slice(0, 3)) {
    riskZones.push([
      `\`${f.name}\``,
      `Fan-out Ce=${f.ce} across ${f.count} modules`,
      `Depends on many things; wide blast radius on change. (dependency-cruiser)`,
    ]);
  }
  // any api / auth / server folder in the churn ranking is inherently sensitive
  for (const [a] of territory.topAreas) {
    if (/\b(api|auth|server|supabase|payment|middleware)\b/.test(a) && riskZones.length < 6) {
      riskZones.push([`\`${a}\``, `Active + sensitive surface`, `Auth / data / server boundary — high cost of a mistake. (git history)`]);
    }
  }

  // first files to read: highest-churn concrete files that still exist
  const firstFiles = territory.topFiles
    .filter(([f]) => existsSync(join(repoRoot, f)))
    .slice(0, 8)
    .map(([f, n]) => `- \`${f}\` — ${n} commits in window`);

  const md = [
    `# Repo Map — ${config.repoLabel || 'repository'}`,
    ``,
    GENERATED,
    ``,
    `> ${stamp}`,
    `>`,
    `> Operational map of the territory, built from cheap deterministic signals (git history + import graph), synthesized for decisions — not an essay. A new developer should know in ~15 min where things live, what is dangerous, and where to start. Refresh with \`npm run repo-map\`.`,
    ``,
    `## 1. TL;DR`,
    ``,
    `- ${config.repoLabel}: ${structure.inventory.length} source modules; the centre of gravity is **\`${topArea[0]}\`** (${topArea[1]} commits in window, ${structure.inventory.find((m) => m.root === config.primaryModule)?.files ?? structure.inventory.reduce((n, m) => n + (m.root.startsWith(config.primaryModule) ? m.files : 0), 0)} files).`,
    `- Work concentrates in a few active areas; most of the tree is comparatively stable.`,
    structure.cycles.length
      ? `- ⚠️ ${structure.cycles.length} import cycle(s) in \`${config.primaryModule}\` — the main structural risk.`
      : `- No import cycles detected in the primary module this run.`,
    `- Scanned window is **the ${windowLabel}**.`,
    ``,
    `### Layers`,
    ``,
    '```mermaid',
    'graph TD',
    layerNodes,
    '```',
    ``,
    `## 2. Terrain — where the project lives`,
    ``,
    `Top active areas (full table in \`artifact-1-territory.md\`):`,
    ``,
    mdTable(['Area', 'Commits'], territory.topAreas.slice(0, 8).map(([a, n]) => [`\`${a}\``, n])),
    ``,
    `## 3. Real coupling — what actually moves together`,
    ``,
    territory.topCo.length
      ? `From git co-change (history) — verify against the import graph before trusting:\n\n` +
        mdTable(['Areas', 'Commits together'], territory.topCo.slice(0, 6).map(([p, n]) => [p.replace(/`/g, ''), n]))
      : `_No strong cross-area co-change in the window._`,
    ``,
    `Structural coupling and cycles live in \`artifact-2-structure.md\` and \`graph/\`.`,
    ``,
    `## 4. Risk zones — where to be careful`,
    ``,
    riskZones.length
      ? mdTable(['Zone', 'What', 'Why it matters (evidence)'], riskZones)
      : '_No high-risk zones flagged this run._',
    ``,
    `## 5. Who to ask`,
    ``,
    mdTable(['Area', 'Ask'], contributors.areaRows),
    ``,
    `## 6. First day — read these first`,
    ``,
    firstFiles.join('\n') || '_n/a_',
    ``,
    `## 7. Limitations — what this map does NOT say`,
    ``,
    `- It is a map of **activity and structure over the ${windowLabel}**, not of correctness or quality.`,
    structure.limitations.map((l) => `- ${l}`).join('\n'),
    ``,
    `---`,
    ``,
    `_Base map generated deterministically. For a specific task, run the \`repo-map\` skill to add a tailored Deep Focus on top of this map instead of re-scanning the whole repo._`,
    ``,
  ].join('\n');

  return md;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------
function generate(targetDir) {
  const gd = join(targetDir, 'graph');
  mkdirSync(gd, { recursive: true });
  const commits = commitsWithFiles(config);
  const territory = scanTerritory(commits);
  const structure = scanStructure(gd);
  const contributors = scanContributors(commits, territory.topAreas);
  const map = synthesize({ territory, structure, contributors });

  writeFileSync(join(targetDir, 'artifact-1-territory.md'), territory.md);
  writeFileSync(join(targetDir, 'artifact-2-structure.md'), structure.md);
  writeFileSync(join(targetDir, 'artifact-3-contributors.md'), contributors.md);
  writeFileSync(join(targetDir, 'repo-map.md'), map);
  return { commits: commits.length, cycles: structure.cycles.length };
}

const check = process.argv.includes('--check');
if (check) {
  // Regenerate into a scratch dir OUTSIDE outDir, then diff only the synthesized
  // markdown (graph JSON is derived and not worth gating CI on). Exit non-zero
  // when stale so the scheduled workflow knows to open a refresh PR.
  const tmp = join(repoRoot, '.repo-map-check');
  rmSync(tmp, { recursive: true, force: true });
  generate(tmp);
  const files = ['repo-map.md', 'artifact-1-territory.md', 'artifact-2-structure.md', 'artifact-3-contributors.md'];
  const { readFileSync } = await import('node:fs');
  const changed = files.filter((f) => {
    try {
      return readFileSync(join(outDir, f), 'utf8') !== readFileSync(join(tmp, f), 'utf8');
    } catch {
      return true;
    }
  });
  rmSync(tmp, { recursive: true, force: true });
  if (changed.length) {
    console.log('Repo map is STALE — run `npm run repo-map`. Changed:', changed.join(', '));
    process.exit(1);
  }
  console.log('Repo map is up to date.');
  process.exit(0);
}

// ensure graph dir exists for the real run (scanStructure writes into it)
mkdirSync(graphDir, { recursive: true });
const result = generate(outDir);
console.log(
  `repo-map: scanned ${result.commits} commits, ${result.cycles} cycle(s) → ${config.outDir}/repo-map.md`
);
