export type StageState = "success" | "failure" | "cancelled" | "blocked" | "superseded" | "na";
export type StagesConfig = { stages: Array<{ name: string; jobs: string[] }>; jobs: Record<string, { name?: string; needs: string[] }> };
export type Stage = { name: string; state: StageState; note?: string; blockedBy?: string };
export type Failure = { stage: string; job: string; jobId: number; jobUrl: string; step: string; excerpt?: string[] };
export type GithubClient = { jobs(attempt: number): Promise<any[]>; attempt(attempt: number): Promise<any>; log(jobId: number): Promise<string> };
export type SlackPayload = { text: string; blocks: any[] };
export const STATUS: Record<string, { emoji: string; label: string }>;
export const STAGE_ICON: Record<StageState, string>;
export function shortTitle(title: string, max?: number): string;
export function splitPr(message: string): { title: string; pr: number | null };
export function duration(sec: number): string;
export function jobIdFor(apiName: string, config: StagesConfig): string | null;
export function resultsFromNeeds(needs: Record<string, { result: string }>): Record<string, string>;
export function resultsFromJobs(jobs: any[], config: StagesConfig): Record<string, string>;
export function blockers(id: string, results: Record<string, string>, config: StagesConfig, seen?: Set<string>): string[];
export function jobState(id: string, results: Record<string, string>, config: StagesConfig): { state: StageState; by?: string[] } | null;
export function classifyStages(results: Record<string, string>, config: StagesConfig, notes?: Record<string, string>, overrides?: Record<string, string>): Stage[];
export function excerptFromLog(raw: string): string[];
export function failuresFromJobs(jobs: any[], config: StagesConfig): Failure[];
export function summarizeStages(stages: Stage[]): string;
export function buildMessage(model: any): SlackPayload;
export function githubClient(env: Record<string, string | undefined>, fetchImpl?: typeof fetch): GithubClient;
export function collect(env: Record<string, string | undefined>, config: StagesConfig, gh: GithubClient, now?: number): Promise<any>;
