export const NPM_VERSION: string;
export function integrity(bytes: Buffer): string;
export function packDirectory(cwd: string, directory: string, sourceSha: string): any;
export function assertFrozenInputs(cwd: string, candidate: any): void;
export function exactCheckout(cwd: string, sha: string): void;
export function validateRegistryResult(metadata: any, bytes: Buffer, candidate: any, tagSha: string): any;
export function publishDirectoryOnce(candidate: any, io: any): Promise<any>;
export function assertReleaseLease(identity: any, dependencies: any): Promise<any>;
export function releaseManifest(input: any): any;
export function registryPackage(version: string): Promise<any>;
export function releaseInputs(env: any): any;
export function npmInvocation(args: string[], context?: { cwd?: string; env?: NodeJS.ProcessEnv }): { command: string; args: string[] };
export function windowsNpmInvocation(wrapper: string, args: string[], context?: { cwd?: string; env?: NodeJS.ProcessEnv }): { command: string; args: string[] };
